version: "3.9"

services:
  postgres:
    image: postgres:16
    environment:
      POSTGRES_DB: supplier_portal
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - data-net
    deploy:
      placement:
        constraints:
          - node.role == manager

  adminer:
    image: adminer:latest
    ports:
      - "8080:8080"
    networks:
      - data-net
    deploy:
      replicas: 1

  kong:
    image: kong:3.7
    environment:
      KONG_DATABASE: "off"
      KONG_DECLARATIVE_CONFIG: /kong/declarative/kong.yml
    ports:
      - "8000:8000"
      - "8001:8001"
    volumes:
      - ./kong/kong.yml:/kong/declarative/kong.yml:ro
    networks:
      - public-net
      - internal-net
    deploy:
      replicas: 1
      placement:
        constraints:
          - node.role == manager

  mock-auth:
    image: nginxdemos/hello:plain-text
    networks:
      - internal-net
    deploy:
      replicas: 2

  mock-catalog:
    image: nginxdemos/hello:plain-text
    networks:
      - internal-net
    deploy:
      replicas: 2

  mock-order:
    image: nginxdemos/hello:plain-text
    networks:
      - internal-net
    deploy:
      replicas: 2

networks:
  public-net:
    driver: overlay
  internal-net:
    driver: overlay
  data-net:
    driver: overlay

volumes:
  postgres_data: