{
 "title": "DepoTrackr Stage2 Services",
 "time": { "from": "now-15m", "to": "now" },
 "panels": [
  {
   "title": "Auth Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(auth_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Catalog Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(catalog_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Order Requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "expr": "sum(rate(order_http_requests_total[1m]))"
    }
   ]
  }
 ]
}